name: "Check Previous Build Integration"

on: pull_request

jobs:
  check-previous_build-integration:

    env:
      BASEDIR: ${{github.workspace}}/..
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout orchestrator
      run: |
        cd $BASEDIR
        git clone https://github.com/arrow-kt/arrow.git --depth 1 --no-single-branch
    - name: Check Build Integration
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH_NAME=${{ github.event.pull_request.head.ref }}
        $BASEDIR/arrow/scripts/check-build-integration.sh $BRANCH_NAME
