name: "Check Previous Doc Integration"

on: pull_request

jobs:
  check-previous_doc-integration:

    env:
      BASEDIR: ${{github.workspace}}/..
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: macos-latest
    timeout-minutes: 90

    steps:
    - uses: actions/checkout@v2
    - name: Checkout orchestrator
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH_NAME=${{ github.event.pull_request.head.ref }}
        git clone https://github.com/arrow-kt/arrow.git $BASEDIR/arrow --depth 1 --no-single-branch
        . $BASEDIR/arrow/scripts/commons4gradle.sh
        updateOrchestrator $BRANCH_NAME
    - name: Check Doc Integration
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH_NAME=${{ github.event.pull_request.head.ref }}
        $BASEDIR/arrow/scripts/check-doc-integration.sh $BRANCH_NAME
